<?php

require_once ( dirname(__FILE__) . '/ftpgallery.database.inc');
require_once ( dirname(__FILE__) . '/ftpgallery.parser.inc');

function ftpgallery_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ftpgallery':
      $output = '<p>' . t("Hello Help.") . '</p>';
 
      return $output;
  }
}

function ftpgallery_node_info() {
  return array(
    'ftpgallery' => array(
      'name' => t('FTP-Gallery'),
      'module' => 'ftpgallery',
      'description' => "Creates a Gallery out of a folder.",
    )
  );
} 

function ftpgallery_init() {
  // Add the Stylesheet
  drupal_add_css(drupal_get_path('module', 'ftpgallery') .'/ftpgallery.css');

//   drupal_add_js(drupal_get_path('module', 'ftpgallery') .'/ftpgallery.js');
}

function ftpgallery_perm() {
  return array(
    'create ftpgallery',
    'edit own ftpgallery',
    'access administration pages'
  );
}

function ftpgallery_access($op, $node, $account) {

  if ($op == 'create') {
    // Only users with permission to do so may create this node type.
    return user_access('create ftpgallery', $account);
  }

  // Users who create a node may edit or delete it later, assuming they have the
  // necessary permissions.
  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own ftpgallery', $account) && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }
}

function ftpgallery_menu() {
  $items = array();

  $items['admin/settings/ftpgallery'] = array(
    'title' => t('FTP Gallery module settings'),
    'description' => t('Settings for the FTP Gallery module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ftpgallery_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ftpgallery.admin.inc',
   );

  // callback for the dynamic ahah form
  $items['ftpgallery/createform/callback'] = array(
    'page callback' => 'ftpgallery_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


// --- The Form ---
function ftpgallery_form(&$node, $form_state) {
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield', 
      '#title' => check_plain($type->title_label), 
      '#required' => TRUE, 
      '#default_value' => $node->title, 
      '#weight' => -5,
    );
  }

  if ($type->has_body) {
    $form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }

  $form['galleryurl'] = array(
    '#type' => 'select',
    '#title' => t('Path to Folder'),
    '#description' => t('Choose path where the gallery is located on the server.'),
    '#required' => TRUE,
    '#options' => drupal_map_assoc(_ftpgallery_readFolders( variable_get('ftpgallery_gallerybasedir', 'files') )),
    '#default_value' => isset($node->galleryurl) ? $node->galleryurl : 0,
    '#ahah' => array(
      'path' => 'ftpgallery/createform/callback',
      'wrapper' => 'dynamic-Content',
    ),
    '#attributes' => array('class' => 'gallery-Id'),
    '#weight' => -1,
  );

  $form['thumbid'] = array(
    '#type' => 'textfield',
    '#title' => t('Thumbnail prefix or Path'),
    '#required' => TRUE,
    '#default_value' => isset($node->thumbid) ? $node->thumbid : 'thumb_',
    '#weight' => 0,
  );

  $form['dynamicContent'] = array(
    '#tree' => TRUE,
    '#prefix' => '<div id="dynamic-Content">',
    '#suffix' => '</div>',
    '#weight' => 0,
  );

  $content = empty($node->galleryurl) ? 
             '<div>test</div>' :
             _ftpgallery_galleryContentPreviewBilder($node->galleryurl);

  $form['dynamicContent']['galleryContent'] = array(
    '#type' => 'markup',
    '#value' => $content,
    '#weight' => 0,
  );

  return $form;
}

function _ftpgallery_readFolders($scanPath){
  $fileNameList = scandir( $scanPath );
  $folderList = array();
  foreach( $fileNameList as $file ){
    if( !is_dir($file) ){
      array_push($folderList, $file);
    }
  }
  return $folderList;
}

function _ftpgallery_galleryContentPreviewBilder($path){

  $folderContent = scandir( variable_get('ftpgallery_gallerybasedir', 'files') . '/' . $path );

  $output = '<div>' ;
  $output .= 'path: ' . $path . '<br />';
  $output .= 'form: ' . $form['values']['galleryurl'] . '<br />';

  foreach($folderContent as $content){
    $output .= $content . '<br />';
  }

  $output .= '</div>';
  return $output;
}

/**
 * This callback has nothing to do with the form itself, so just returns a bit
 * of HTML that will replace the existing markup in $form['box'].
 */
function ftpgallery_callback() {
  $form = ftpgallery_callback_helper();

  $changed_elements = $form['dynamicContent'];

  // Prevent duplicate wrappers.
  unset($changed_elements['#prefix'], $changed_elements['#suffix']);

  $output = theme('status_messages') . drupal_render($changed_elements);

//   $output = 'my test output <br />' . $form['values']['galleryurl'];

  drupal_json(array('status' => TRUE, 'data' => $output));
  exit();
}


/**
 * Does the very standard things that must be done in any normal callback.
 * Used by each callback in this example module.
 */
function ftpgallery_callback_helper() {
  $form_state = array('storage' => NULL, 'submitted' => FALSE);
  $form_build_id = $_POST['form_build_id'];
  $form = form_get_cache($form_build_id, $form_state);
  $args = $form['#parameters'];
  $form_id = array_shift($args);
  $form_state['post'] = $form['#post'] = $_POST;
  // Enable the submit/validate handlers to determine whether AHAH-submittted.
  $form_state['ahah_submission'] = TRUE;
  $form['#programmed'] = $form['#redirect'] = FALSE;
  drupal_process_form($form_id, $form, $form_state);
  $form = drupal_rebuild_form($form_id, $form_state, $args, $form_build_id);
  return $form;
}

function ftpgallery_nodeapi(&$node, $op, $teaser, $page) {
  switch ($op) {
    case 'delete revision':
      // Notice that we're matching a single revision based on the node's vid.
      db_query('DELETE FROM {ftpgallery} WHERE vid = %d', $node->vid);
      break;
  }
}

// --- Display ---
function ftpgallery_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);

  $node = _ftpgallery_getGalleryPictures($node);

  $node->content['gallery'] = array(
    '#value' => theme('ftpgallery_gallery', $node),
    '#weight' => 1,
  );

  $errors = drupal_get_messages( 'error', FALSE);
  if( !empty($errors) && $page ){
    _ftpgallery_debug($node);
  }

  return $node;
}

function _ftpgallery_getGalleryPictures($node){
  if( !_ftpgallery_galleryPathExists($node) ){
     drupal_set_message(t('Gallery path does not exist.'), 'error');
     return $node;
  }

  // here we get the Pictures. See ftpgallery.parser.inc for the parsing.
  $node = _ftpgallery_parseGalleryFolder($node);

  if( count($node->gallery['thumbnails']) != count($node->gallery['pictures']) ){
    drupal_set_message(t('Not equal number of thumbnails and pictures.'), 'warning');
  }

  if( count($node->gallery['thumbnails']) == 0 ){
    drupal_set_message(t('No Pictures or no matching thumbnails in the Folder.'), 'error');
  }

  return $node;
}

function _ftpgallery_galleryPathExists($node, $file = ''){
  if( empty($node->galleryurl) ){
    return false;
  }
  return file_exists( getcwd() . "/" . _ftpgallery_galleryPath($node) . $file );
}

function _ftpgallery_galleryPath($node){
  $baseDir = variable_get('ftpgallery_gallerybasedir', 'files');
  return $baseDir . "/" . $node->galleryurl . "/";
}

// Tell Drupal about the theme functions
function ftpgallery_theme() {
  return array(
    'ftpgallery_gallery' => array(
      'arguments' => array('node'),
    ),
    'ftpgallery_formatLightboxImage' => array(
      'arguments' => array('pictureUrl', 'thumbnailUrl', 'lightboxGroup', 'alt', 'title' , 'attributes'),
    ),
  );
}

function theme_ftpgallery_gallery($node) {
  $output = '<div class="ftpgallery_gallery">';
  $galleryPath = _ftpgallery_galleryPath($node);

  // we have the same amount of thumbnails and pictures. see parser.
  for ($i = 0; $i < count($node->gallery['thumbnails']); $i++) {
    $output .= theme_ftpgallery_formatLightboxImage(
      $galleryPath . $node->gallery['pictures'][$i],
      $galleryPath . $node->gallery['thumbnails'][$i],
      $node->nid,
      $node->gallery['thumbnails'][$i]
    );
  }
  $output .= '</div>';
  return $output;
}

function theme_ftpgallery_formatLightboxImage($pictureUrl, $thumbnailUrl, $lightboxGroup, $alt='', $title='' , $attributes = NULL){
    $output .= '<a href="' . $pictureUrl . '" ';

    $output .= 'rel="lightbox[';
    $output .= $lightboxGroup;
    $output .= ']"> ';

    $attributes['class'] = 'lightboxThumbnail';

    $output .=  theme('image', $thumbnailUrl, $alt, $title, $attributes, FALSE);

    $output .= '</a>';
    return $output;
}


// Add some debug information, when somthing goes wrong.
function _ftpgallery_debug($node) {
  drupal_set_message(t(" *** Debug info *** "), 'error');

  drupal_set_message(t("Thumbnail prefix: %thumb",
                     array('%thumb' => $node->thumbid)), 'error');

  drupal_set_message(t("Allowed file types: %types",
                     array('%types' =>  variable_get('ftpgallery_allowedfiletypes', 'jpg jpeg png'))), 'error');

  drupal_set_message(t("Gallery path: %path",
                     array('%path' =>  _ftpgallery_galleryPath($node))), 'error');
}