<?php

require_once ( dirname(__FILE__) . '/ftpgallery.database.inc');
require_once ( dirname(__FILE__) . '/ftpgallery.settings.inc');
require_once ( dirname(__FILE__) . '/ftpgallery.errorhandling.inc');

function ftpgallery_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ftpgallery':
      $output = '<p>' . t("Hello Help.") . '</p>';
 
      return $output;
  }
}

function ftpgallery_node_info() {
  return array(
    'ftpgallery' => array(
      'name' => t('FTP-Gallery'),
      'module' => 'ftpgallery',
      'description' => "Creates a Gallery out of a folder.",
    )
  );
} 

function ftpgallery_perm() {
  return array(
    'create ftpgallery',
    'edit own ftpgallery',
    'access administration pages'
  );
}

function ftpgallery_access($op, $node, $account) {

  if ($op == 'create') {
    // Only users with permission to do so may create this node type.
    return user_access('create ftpgallery', $account);
  }

  // Users who create a node may edit or delete it later, assuming they have the
  // necessary permissions.
  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own ftpgallery', $account) && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }
}

function ftpgallery_menu() {
  $items = array();

  $items['admin/settings/ftpgallery'] = array(
    'title' => t('FTP Gallery module settings'),
    'description' => t('Settings for the FTP Gallery module.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ftpgallery_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

// --- The Form ---
function ftpgallery_form(&$node, $form_state) {
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield', 
      '#title' => check_plain($type->title_label), 
      '#required' => TRUE, 
      '#default_value' => $node->title, 
      '#weight' => -5,
    );
  }

  if ($type->has_body) {
    // In Drupal 6, we use node_body_field() to get the body and filter
    // elements. This replaces the old textarea + filter_form() method of
    // setting this up. It will also ensure the teaser splitter gets set up
    // properly.
    $form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }

  // Now we define the form elements specific to our node type.
  $form['galleryurl'] = array(
    '#type' => 'textfield', 
    '#title' => t('Path to Folder'), 
    '#required' => TRUE,
    '#default_value' => isset($node->galleryurl) ? $node->galleryurl : '',
  );

  return $form;
}

function ftpgallery_validate($node, &$form_state) {

  if (!_ftpgallery_galleryPathExist($node)) {
    form_set_error('galleryurl', t('The path for the gallery does not exist. Please use a valid path.'));
  }

}

function _ftpgallery_galleryPathExist($node) {
  return file_exists( getcwd() . "/" . $node->galleryurl );
}


// --- Display ---
function ftpgallery_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);

  $node = _ftpgallery_getGalleryPictures($node);

  $node->content['gallery'] = array(
    '#value' => theme('ftpgallery_gallery', $node),
    '#weight' => 1,
  );

  if( !empty($node->error) ){
    $node->content['error'] = array(
      '#value' => theme('ftpgallery_error', $node),
      '#weight' => 2,
    );
  }

  return $node;
}

function _ftpgallery_getGalleryPictures($node){
  if( !_ftpgallery_galleryPathExist($node) ){
     return _ftpgallery_formatError($node, t('Gallery path does not exist.'));
  }

  $node = _ftpgallery_parseGalleryFolder($node);

  if( count($node->gallery['thumbnails']) != count($node->gallery['pictures']) ){
    $node = _ftpgallery_formatError($node, t('Not equal number of thumbnails and pictures.'), true);
  }

  if( count($node->gallery['thumbnails']) == 0 ){
    $node = _ftpgallery_formatError($node, t('No matching pictures in the Folder.'), true);
  }

  return $node;
}

function _ftpgallery_parseGalleryFolder($node) {
  $thumbnails = array();
  $pictures = array();

  // get files in the gallery folder
  $filePathArray = scandir($node->galleryurl);

  foreach($filePathArray as $filePath) {
    if( _ftpgallery_isValidFileType($filePath) ) {
      if( _ftpgallery_isThunbnail($filePath) ) {
        array_push($thumbnails, $filePath);
      } else {
        array_push($pictures, $filePath);
      }
    }
  }

  $node->gallery = array();
  $node->gallery['thumbnails'] = $thumbnails;
  $node->gallery['pictures'] = $pictures;
  return $node;
}

function _ftpgallery_isValidFileType($file){
  $allowedFileTypes = variable_get('ftpgallery_allowedfiletypes', 'jpg jpeg png');
  $allowedFileTypes = explode(" ", $allowedFileTypes);

  $fileNameEnding = strtolower(end(explode(".", $file)));

  foreach($allowedFileTypes as $ending){
    if( $fileNameEnding == $ending ) {
      return true;
    }
  }
  return false;
}

function _ftpgallery_isThunbnail($file){
  // TODO make a settingspage
  $thumbnailPrefix = "thumb";

  $filePrefix = reset(explode("_", $file));

  return ( $filePrefix == $thumbnailPrefix );
}

function theme_ftpgallery_gallery($node) {
  $output = '<div class="ftpgallery_gallery">';

  // we only display pictures with a thumbnail.
  for ($i = 0; $i < count($node->gallery['thumbnails']); $i++) {
    $output .= '<a href="';
    $output .= $node->galleryurl . "/" . $node->gallery['pictures'][$i];
    $output .= '"';

    $output .= 'rel="lightbox[';
    $output .= $node->nid;
    $output .= ']">';

    $url = $node->galleryurl . "/" . $node->gallery['thumbnails'][$i];
    $alt = $node->gallery['thumbnails'][$i];
    $title = $node->gallery['thumbnails'][$i];
    $attributes = 'width="120" height="120"';

    $output .=  theme('image', $url, $alt, $title, $attributes, FALSE);

    $output .= '</a>';
  }
  $output .= '</div>';
  return $output;
}

// Tell Drupal about the theme functions
function ftpgallery_theme() {
  return array(
    'ftpgallery_error' => array(
      'arguments' => array('text'),
    ),
    'ftpgallery_gallery' => array(
      'arguments' => array('node'),
    ),
  );
}
